/* Generated by tools/gen-api-types.py from memai/admin_schemas.py; run it again instead of editing this file. */

export interface Ok {
  ok: true;
}

export interface Scoped {
  domain_scope?: string[];
}

export interface Totals {
  memories: number;
  active: number;
  archived: number;
  relations: number;
  edits: number;
  sessions: number;
  domains: number;
}

export interface Symptom {
  key: string;
  severity: string;
  count: number;
  share: number;
  params: Record<string, string>;
  of?: number;
}

export interface DayCount {
  day: string;
  count: number;
}

export interface DbFile {
  project: string;
  path: string;
  size: number;
  wal_size: number;
}

export interface HealthScore {
  score: number;
  axes: Record<string, number>;
  active: number;
  delta: number | null;
  delta_days: number;
  since: string | null;
}

export interface Overview {
  totals: Totals;
  by_type: Record<string, number>;
  by_confidence: Record<string, number>;
  by_type_confidence: Record<string, Record<string, number>>;
  open_tasks: number;
  health: HealthScore;
  symptoms: Symptom[];
  activity: DayCount[];
  domains: Record<string, unknown>[];
  recent: Record<string, unknown>[];
  db: DbFile;
}

export interface Projects {
  active: string;
  projects: Record<string, unknown>[];
}

export interface ProjectCreated {
  active: string;
  projects: Record<string, unknown>[];
  ok: true;
  name: string;
}

export interface ProjectDeleted {
  active: string;
  projects: Record<string, unknown>[];
  ok: true;
}

export interface ProjectActivated {
  ok: true;
  active: string;
}

export interface ProjectMove {
  dry_run: boolean;
  source: string;
  target: string;
  creates: boolean;
  memories: number;
  diagrams: number;
  tasks: number;
  relations: number;
  edits: number;
  conflicts: string[];
  unknown: string[];
  outside: unknown;
  moved?: number;
  backup?: string;
  errors?: unknown[];
}

export interface MemoryPage {
  domain_scope?: string[];
  total: number;
  items: Record<string, unknown>[];
  searched: boolean;
}

export interface MemoryCreated {
  uid: string;
  also: string[];
}

export interface SectionSpec {
  key: string;
  label: string;
  max_len: number;
}

export interface TaskRecord {
  goal: string;
  state: string;
  completed_at: string;
  items: Record<string, unknown>[];
  comments: Record<string, unknown>[];
  notes: Record<string, unknown>[];
}

export interface DiagramRecord {
  uid: string;
  kind: string;
  title: string;
  summary: string;
  font_scale: number;
  nodes: Record<string, unknown>[];
  edges: Record<string, unknown>[];
  links: Record<string, unknown>[];
  jumps: Record<string, unknown>[];
  mermaid: string;
}

export interface MemoryRecord {
  rowid_pk: number;
  uid: string;
  type: string;
  title: string;
  content: string;
  domain: string;
  also?: string[];
  tags: string;
  session: string;
  status: string;
  confidence: string;
  pin: string;
  superseded_by: string | null;
  review_after: string;
  source_ref: string;
  created_at: string;
  updated_at: string;
  recalls: number;
  last_recall: string | null;
  edit_history: Record<string, unknown>[];
  spec: SectionSpec[];
  sections: Record<string, unknown>[];
  section_problem: string;
  body_links: Record<string, Record<string, unknown>>;
  relations: Record<string, unknown>[];
  superseded_by_peer?: Record<string, unknown> | null;
  task?: TaskRecord | null;
  diagram?: DiagramRecord | null;
  referenced_by_diagrams?: Record<string, unknown>[];
}

export interface MetaSaved {
  ok: true;
  changed: string[];
  also?: string[];
}

export interface PinSaved {
  ok: true;
  pin: string;
}

export interface Purged {
  ok: true;
  backup: string;
  purged: number;
  missing: string[];
}

export interface BulkDone {
  ok: true;
  affected: number;
}

export interface TaskAnswer {
  task: TaskRecord | null;
  status: string;
}

export interface TaskCreated {
  task: TaskRecord | null;
  status: string;
  uid: string;
}

export interface RelationCreated {
  relation_id: number;
}

export interface Graph {
  domain_scope?: string[];
  nodes: Record<string, unknown>[];
  edges: Record<string, unknown>[];
  total: number;
  truncated: boolean;
}

export interface DiagramPage {
  domain_scope?: string[];
  total: number;
  with_issues: number;
  items: Record<string, unknown>[];
}

export interface DiagramCreated {
  uid: string;
  also: string[];
}

export interface NodeSaved {
  ok: true;
  key: string;
}

export interface LayoutSaved {
  ok: true;
  moved: number;
}

export interface Mermaid {
  uid: string;
  mermaid: string;
}

export interface UpdateState {
  current: string;
  latest: string;
  behind: number;
  url: string;
  checked_at: string;
  failed: boolean;
  enabled: boolean;
  interval_hours: number;
  commands: string[];
}

export interface Changelog {
  current: string;
  releases: Record<string, unknown>[];
  update: UpdateState;
  source: boolean;
}

export interface ConfigSaved {
  domain_case: string;
  svg_retention: string;
  warden_enabled: boolean;
  warden_minutes: number;
  task_ask_enabled: boolean;
  task_ask_minutes: number;
}

export interface Config {
  domain_case: string;
  svg_retention: string;
  warden_enabled: boolean;
  warden_minutes: number;
  task_ask_enabled: boolean;
  task_ask_minutes: number;
  sections: Record<string, SectionSpec[]>;
}

export interface DomainEntry {
  domain: string;
  active: number;
  archived: number;
  types: Record<string, number>;
  latest_at: string;
  parent: string;
  depth: number;
  children: number;
  subtree_active: number;
  subtree_archived: number;
  also: number;
  subtree_also: number;
  subtree_latest_at: string;
  implicit: boolean;
  collides_with?: string[];
}

export interface DomainTree {
  domains: DomainEntry[];
}

export interface DomainDetail {
  domain: string;
  filed: Record<string, unknown>[];
  filed_total: number;
  crossing: Record<string, unknown>[];
}

export interface DomainRenamed {
  ok: true;
  affected: number;
  also_affected: number;
  domains: number;
  merged: unknown;
}

export interface NormalizePlan {
  mode: string;
  dry_run: true;
  plan: Record<string, unknown>[];
  renames: number;
  merges: number;
}

export interface NormalizeDone {
  ok: true;
  mode: string;
  moved: number;
  affected: number;
  also_affected: number;
}

export interface DomainStatusSaved {
  ok: true;
  affected: number;
  domains: number;
  uids: string[];
}

export interface DomainDeleted {
  ok: true;
  purged: number;
  unlinked: number;
  domains: number;
}

export interface Check {
  ok: boolean;
  detail: string;
}

export interface FtsCheck {
  ok: boolean;
  detail: string;
  rows: number;
  expected: number;
}

export interface OrphanCount {
  orphans: number;
}

export interface TagCount {
  untagged: number;
  active: number;
}

export interface TitleCount {
  untitled: number;
  active: number;
}

export interface RendersUsage {
  files: number;
  bytes: number;
}

export interface Renders {
  files: number;
  bytes: number;
  retention: string;
  path: string;
}

export interface StoreFile {
  path: string;
  size: number;
  wal_size: number;
  reclaimable: number;
  compact_reason: string;
}

export interface Health {
  project: string;
  integrity: Check;
  fts: FtsCheck;
  relations: OrphanCount;
  tags: TagCount;
  title: TitleCount;
  renders: Renders;
  file: StoreFile;
  backups: Record<string, unknown>[];
}

export interface FtsRebuilt {
  ok: true;
  rows: number;
}

export interface OrphansCleaned {
  ok: true;
  relations_removed: number;
  suggestions_removed: number;
  node_links_removed: number;
  jumps_removed: number;
  task_links_removed: number;
}

export interface RendersPruned {
  ok: true;
  pruned: number;
  bytes: number;
  mode: string;
  before: RendersUsage;
  after: RendersUsage;
}

export interface Vacuumed {
  ok: true;
  before: number;
  after: number;
}

export interface BackupTaken {
  ok: true;
  project: string;
  path: string;
  size: number;
}

export interface Backups {
  project: string;
  shelf: Record<string, unknown>[];
  archives: Record<string, unknown>[];
}

export interface ArchivePlanEntry {
  name: string;
  added: number;
  exists: boolean;
}

export interface ArchivePlan {
  ok: true;
  plan: ArchivePlanEntry[];
}

export interface Archived {
  ok: true;
  archive: string;
  archives: Record<string, unknown>[];
  added: number;
  raw: number;
  size: number;
}

export interface Unarchived {
  ok: true;
  name: string;
  restored: unknown;
}

export interface ArchiveDeleted {
  ok: true;
  name: string;
  count: number;
}

export interface Renamed {
  ok: true;
  name: string;
}

export interface BackupNamed {
  ok: true;
  name: string;
  label: string;
}

export interface BackupPinned {
  ok: true;
  name: string;
  pinned: boolean;
}

export interface BackupsDeleted {
  ok: true;
  deleted: number;
  freed: number;
}

export interface BackupRestored {
  ok: true;
  name: string;
  kept: string;
}

export interface DedupPairs {
  domain_scope?: string[];
  pairs: Record<string, unknown>[];
  threshold: number;
}

export interface Sectionized {
  ok: true;
  backup: string;
  total: number;
  conformed: number;
  rewritten: number;
  needs_review: number;
}

export interface SectionQueue {
  ok: true;
  migrated: boolean;
  unread: number;
  queue: Record<string, unknown>[];
}

export interface OptimizationRun {
  id: number;
  created_at: string;
  note: string;
  status: string;
  backup_path: string | null;
}

export interface OptimizationRuns {
  runs: Record<string, unknown>[];
}

export interface Suggestions {
  run: OptimizationRun;
  runs: OptimizationRun[];
  suggestions: Record<string, unknown>[];
}

export interface Ledger {
  memories: number;
  active: number;
  domains: number;
  relations: number;
  confirmed: number;
  archived: number;
  chars: number;
}

export interface OptimizationSummary {
  run: OptimizationRun;
  total: number;
  pending: number;
  verified: number;
  ledger: Ledger;
  groups: Record<string, unknown>[];
}

export interface Applied {
  ok: true;
  backup: unknown;
}

export interface AppliedAll {
  ok: true;
  applied: number;
  failed: unknown[];
  backup: string | null;
  backups: string[];
}

export interface RejectedAll {
  ok: true;
  rejected: number;
}

export interface AuditLog {
  entries: Record<string, unknown>[];
}

export interface Lookup {
  items: Record<string, unknown>[];
  has_more: boolean;
}
