"""The dashboard's own pages: the built UI, its font stylesheet, and the ping."""

from __future__ import annotations

import os
from pathlib import Path

from starlette.responses import FileResponse, JSONResponse, Response
from starlette.routing import Route

from memai import __version__, update
from memai.store import paths

# The dashboard as served: the Vite build output, not its sources. `npm run
# build` writes it; an install that skipped that step has no directory here.
WEBUI_DIR = Path(__file__).parents[1] / "webui" / "dist"


async def index(request):
    """The built dashboard, or what to run when it has not been built."""
    page = WEBUI_DIR / "index.html"
    if not page.is_file():
        return Response(
            "The dashboard is not built. Run `npm ci && npm run build` in the "
            "repository root, then reload.",
            status_code=503, media_type="text/plain")
    return FileResponse(page)


async def ping(request):
    """Say who is answering, so a probe can tell this apart from anything else.

    autostart.py needs to know whether the thing on a port is a MemAI
    dashboard before it decides not to start one -- on the machine this
    was written for, the admin's own default port was held by an
    unrelated MCP server. An open TCP port proves nothing; this reply
    does. Unauthenticated on purpose: it says only what a connection
    attempt already reveals.
    """
    return JSONResponse({
        "app": "memai",
        "version": __version__,
        "pid": os.getpid(),
        "project": paths.active_project(),
        "db": str(paths.default_db_path()),
        # install-guard.py compares it with its own checkout before refusing
        "root": str(update.checkout_root() or ""),
    })


# (family, weight, filename, names an installed copy may go by)
WEBFONTS = (
    ("Roboto", 400, "roboto-400.woff2", ("Roboto", "Roboto Regular")),
    ("Roboto", 500, "roboto-500.woff2", ("Roboto Medium", "Roboto")),
    ("Roboto", 700, "roboto-700.woff2", ("Roboto Bold", "Roboto")),
    ("Roboto Mono", 400, "roboto-mono-400.woff2", ("Roboto Mono", "Roboto Mono Regular")),
    ("Roboto Mono", 500, "roboto-mono-500.woff2", ("Roboto Mono Medium", "Roboto Mono")),
    ("Roboto Mono", 600, "roboto-mono-600.woff2", ("Roboto Mono SemiBold", "Roboto Mono")),
)


async def fonts_css(request):
    """@font-face rules, naming a file only when that file is really there.

    webui/public/fonts/ ships with the repo, so the normal case is that every
    face is present. The existence check stays because a url() in a static
    stylesheet is a request whether the file is there or not: a checkout
    someone pruned, or a face a future release renames, would log 404s in
    the console for something otherwise working. Generating the rules means
    an absent face degrades to a local()-only src -- still used if the
    system has it, never fetched, and quiet either way.

    The BUNDLED file comes FIRST, and that order is load-bearing. "Roboto"
    names several releases whose advance widths differ -- an installed copy
    measured x at 1030 units where the bundled face measures 1016 -- so
    preferring local() meant the canvas broke a node label in a different
    place on a machine that happened to have Roboto installed.
    diagram_svg.measure() reads a width table extracted from the file in
    webui/public/fonts/ (tools/gen-roboto-metrics.py), so the canvas has to be
    looking at that same file for the two renderers to wrap alike. local()
    stays as the fallback for a checkout missing the file, where nothing
    can be guaranteed anyway.
    """
    fonts_dir = WEBUI_DIR / "fonts"
    lines = ["/* generated by memai.admin -- populate with tools/fetch-fonts.py */"]
    for family, weight, filename, local_names in WEBFONTS:
        src = []
        if (fonts_dir / filename).is_file():
            src.append(f"url('/static/fonts/{filename}') format('woff2')")
        src += [f"local('{name}')" for name in local_names]
        lines.append(
            f"@font-face {{ font-family: '{family}'; font-style: normal; "
            f"font-weight: {weight}; font-display: swap; src: {', '.join(src)}; }}")
    return Response("\n".join(lines) + "\n", media_type="text/css")


ROUTES = [
    Route("/", index),
    Route("/fonts.css", fonts_css),
    Route("/api/ping", ping),
]
