"""Writes src/memai/webui/api/types.ts from the response TypedDicts in memai/admin_schemas.py.

    python tools/gen-api-types.py           # rewrite the file
    python tools/gen-api-types.py --check   # exit 1 when the file is stale
"""

from __future__ import annotations

import argparse
import json
import sys
import types
from pathlib import Path
from typing import Any, Literal, Union, get_args, get_origin, get_type_hints, is_typeddict

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from memai import admin_schemas  # noqa: E402

OUT = ROOT / "src" / "memai" / "webui" / "api" / "types.ts"
HEADER = ("/* Generated by tools/gen-api-types.py from memai/admin_schemas.py; "
          "run it again instead of editing this file. */\n")
PRIMITIVES = {str: "string", int: "number", float: "number", bool: "boolean", type(None): "null"}


def ts(hint: Any) -> str:
    """The TypeScript spelling of one annotation."""
    if hint is Any:
        return "unknown"
    if hint in PRIMITIVES:
        return PRIMITIVES[hint]
    if is_typeddict(hint):
        return hint.__name__
    origin, args = get_origin(hint), get_args(hint)
    if origin is Literal:
        return " | ".join(json.dumps(a) for a in args)
    if origin in (Union, types.UnionType):
        return " | ".join(ts(a) for a in args)
    if origin is list:
        inner = ts(args[0])
        return f"({inner})[]" if " | " in inner else f"{inner}[]"
    if origin is dict:
        return f"Record<string, {ts(args[1])}>"
    raise TypeError(f"no TypeScript spelling for {hint!r}")


def interface(cls: type) -> str:
    hints = get_type_hints(cls)
    optional: frozenset[str] = getattr(cls, "__optional_keys__", frozenset())
    fields = [f"  {key}{'?' if key in optional else ''}: {ts(hint)};" for key, hint in hints.items()]
    return "\n".join([f"export interface {cls.__name__} {{", *fields, "}"])


def render() -> str:
    shapes = [obj for obj in vars(admin_schemas).values()
              if is_typeddict(obj) and obj.__module__ == admin_schemas.__name__]
    return HEADER + "\n" + "\n\n".join(interface(cls) for cls in shapes) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    text = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current.replace("\r\n", "\n") != text:
            print(f"{OUT.relative_to(ROOT)} is stale: run python tools/gen-api-types.py", file=sys.stderr)
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
