#!/usr/bin/env python3
"""Emit src/memai/roboto_metrics.json from the woff2 faces the admin UI uses.

Run by hand, and only when the font files change:

    python tools/gen-roboto-metrics.py

Why this exists. The admin canvas decides where a node label wraps by
asking the browser to measure the text (diagram-engine.js, wrap()). The
server-side SVG renderer has to reach the SAME decision without a canvas,
or a diagram drawn in the chat breaks its lines in different places than
the same diagram drawn in the dashboard -- which is the one thing the SVG
export exists to avoid. So the widths are extracted once, here, and read
at runtime from a plain JSON table.

The generated table is COMMITTED, unlike the fonts themselves: the woff2
files are deliberately untracked (see tools/fetch-fonts.py), so a
renderer that needed them at runtime would work only on the machines that
had run that script. Advance widths are a few kilobytes of numbers and
they never change for a released font.

Only the latin subset is present, because that is all fetch-fonts.py
downloads. That covers every accented character the UI and its
translations have needed so far -- Portuguese included, whose diacritics
all live below U+0100. A codepoint the table does not know falls back to
the font's own .notdef advance; see diagram_svg.measure().

Needs fontTools and brotli, which are NOT runtime dependencies:

    pip install "fonttools>=4.50" "brotli>=1.1"

Roboto & Roboto Mono (c) Google, licensed Apache-2.0. What lands in the
repository is advance widths -- measurements taken from the faces, not
the faces themselves.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "src" / "memai" / "webui" / "fonts"
OUT = ROOT / "src" / "memai" / "roboto_metrics.json"

# role -> (file, the family name the canvas passes to ctx.font)
FACES = {
    "ui": ("roboto-400.woff2", "Roboto"),
    "mono": ("roboto-mono-400.woff2", "Roboto Mono"),
}

# Regular weight only. Every label and badge the diagram draws is set at
# 400 (see FONT_UI / FONT_MONO in diagram-engine.js); the 500/700 faces
# fetch-fonts.py also downloads are used by chrome the canvas never draws.


def _face_metrics(path: Path, family: str) -> dict:
    from fontTools.ttLib import TTFont

    font = TTFont(str(path), lazy=True)
    upem = int(font["head"].unitsPerEm)
    hmtx = font["hmtx"]
    # best_cmap() picks the unicode subtable, so the keys are codepoints
    # rather than whatever glyph order the file happens to use
    cmap = font.getBestCmap()

    widths: dict[str, int] = {}
    for code, glyph in cmap.items():
        if glyph in hmtx.metrics:
            widths[str(code)] = int(hmtx.metrics[glyph][0])

    # What an unknown codepoint measures. Not what a browser does -- it
    # falls back to another installed font, whose advance we cannot know
    # here -- but the font's own answer for "no glyph", which keeps the
    # arithmetic honest and bounded instead of silently measuring zero.
    notdef = int(hmtx.metrics[".notdef"][0]) if ".notdef" in hmtx.metrics else (
        round(sum(widths.values()) / len(widths)) if widths else upem // 2
    )
    font.close()
    return {"family": family, "units_per_em": upem, "notdef": notdef,
            "widths": dict(sorted(widths.items(), key=lambda kv: int(kv[0])))}


def main() -> int:
    missing = [f for f, _ in FACES.values() if not (FONT_DIR / f).is_file()]
    if missing:
        print(f"missing in {FONT_DIR}: {', '.join(missing)}\n"
              f"  run python tools/fetch-fonts.py first", file=sys.stderr)
        return 1
    try:
        import fontTools  # noqa: F401
    except ModuleNotFoundError:
        print('needs fontTools: pip install "fonttools>=4.50" "brotli>=1.1"',
              file=sys.stderr)
        return 1

    out = {
        "_": "Generated by tools/gen-roboto-metrics.py -- do not edit by hand.",
        "_font": ("Roboto & Roboto Mono (c) Google, Apache-2.0. Advance widths "
                  "extracted from the latin subset; the faces themselves are "
                  "untracked (tools/fetch-fonts.py)."),
    }
    for role, (filename, family) in FACES.items():
        out[role] = _face_metrics(FONT_DIR / filename, family)
        print(f"  {role:4} {family:12} {len(out[role]['widths']):4} glyphs, "
              f"upem {out[role]['units_per_em']}")

    OUT.write_text(json.dumps(out, indent=1, ensure_ascii=True) + "\n",
                   encoding="utf-8")
    print(f"\n{OUT.relative_to(ROOT)}  {OUT.stat().st_size / 1024:.1f} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
